@exercise = Exercise(1)

### list all sets for certain exercise
GET http://localhost:3000/set_numbers
Content-Type: application/json


### list all unique exercise titles
GET http://localhost:3000/set_numbers/2
Content-Type: application/json

### create exercise
POST http://localhost:3000/set_numbers
Content-Type: application/json

{
    "exercise": {
        "title": "Squat"
    }
    
}

### update set
PATCH http://localhost:3000/set_numbers/1
Content-Type: application/json

{
    "set_number": {
        "reps": 10,
        "weight": 100,
        "exercise_id": 1
    }
    
}

### delete set
DELETE http://localhost:3000/set_numbers/2
Content-Type: application/json

### create user
POST http://localhost:3000/authenticate
Content-Type: application/json

{
    "username": "Steve",
    "password": "blah"
}

### Create a user
GET http://localhost:3000/users/sign_up
Content-Type: application/json

{
    "name": "Steve5",
    "username": "Steve5",
    "email": "steve5@test.com",
    "password": "password",
    "password_confirmation": "password"
}

### Get a user
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Steve5",
    "username": "Steve5",
    "email": "steve5@test.com",
    "password": "password",
    "password_confirmation": "password"
}